### Users Index
GET http://localhost:3000/users.json

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Dummy",
  "email": "dummy@test.com",
  "password": "password",
  "profile_pic": "Dummy.jpg"
}

###Users Show
GET http://localhost:3000/users/3.json
Content-Type: application/json

###Users Update
PATCH http://localhost:3000/users/3.json
Content-Type: application/json

{
  "username": "TheRealJoeSchmoe",
  "email": "joe@test.com",
  "password": "password",
  "profile_pic": "https://images.freeimages.com/images/large-previews/b29/normal-guy-1438830.jpg"
}

###Users Destroy
DELETE http://localhost:3000/users/5.json
Content-Type: application/json

############################################

###Uploads index
GET http://localhost:3000/uploads.json

###Uploads Create
POST http://localhost:3000/uploads.json
Content-Type: application/json

{
  "title": "New Grill",
  "description": "I figured I would take my new grill for a test drive",
  "image": "https://www.bowrivermeatmarket.ca/wp-content/uploads/2021/03/order-meat-online-1-1024x683.jpg",
  "user_id": 3
}

###Uploads Show
GET http://localhost:3000/uploads/2.json
Content-Type: application/json

###Uploads Update
PATCH http://localhost:3000/uploads/2.json
Content-Type: application/json

{
  "title": "New Grill",
  "description": "I figured I would take my new grill for a test drive.",
  "image": "https://www.bowrivermeatmarket.ca/wp-content/uploads/2021/03/order-meat-online-1-1024x683.jpg",
  "user_id": 3
}

###Uploads Destroy
DELETE http://localhost:3000/uploads/3.json
Content-Type: application/json

############################################

###Comments Index
GET http://localhost:3000/comments.json
Content-Type: application/json