### Users Index
GET http://localhost:3000/users.json

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "SoulReaper",
  "email": "ichigo@test.com",
  "password": "password",
  "profile_pic": "https://images4.fanpop.com/image/photos/15900000/Ichigo-kurosaki-ichigo-15958160-750-1000.jpg"
}

###Users Show
GET http://localhost:3000/users/3.json
Content-Type: application/json

###Users Update
PATCH http://localhost:3000/users/3.json
Content-Type: application/json

{
  "username": "TheRealJoeSchmoe",
  "email": "joe@test.com",
  "password": "password",
  "profile_pic": "https://images.freeimages.com/images/large-previews/b29/normal-guy-1438830.jpg"
}