### Users Index
GET http://localhost:3000/users.json

### Users Create Password and email blank for some reason
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Dummy",
  "email": "dummy@test.com",
  "profile_pic": "Dummy.jpg",
  "password": "password",
  "password_confirmation": "password"
}

###Users Show
GET http://localhost:3000/users/3.json
Content-Type: application/json

###Users Update
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{
  "username": "SubSoulReaper",
  "email": "ichigo@test.com",
  "profile_pic": "https://images4.fanpop.com/image/photos/15900000/Ichigo-kurosaki-ichigo-15958160-750-1000.jpg",
  "password": "password",
  "password_confirmation": "password"

}

###Users Destroy
DELETE http://localhost:3000/users/5.json
Content-Type: application/json


###Users Login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "luffy@test.com",
  "password": "password"
}
############################################

###Uploads index
GET http://localhost:3000/uploads.json

###Uploads Create
POST http://localhost:3000/uploads.json
Content-Type: application/json

{
  "title": "New Grill",
  "description": "I figured I would take my new grill for a test drive",
  "image": "https://www.bowrivermeatmarket.ca/wp-content/uploads/2021/03/order-meat-online-1-1024x683.jpg",
  "user_id": 3
}

###Uploads Show
GET http://localhost:3000/uploads/2.json
Content-Type: application/json

###Uploads Update
PATCH http://localhost:3000/uploads/2.json
Content-Type: application/json

{
  "title": "New Grill",
  "description": "I figured I would take my new grill for a test drive.",
  "image": "https://www.bowrivermeatmarket.ca/wp-content/uploads/2021/03/order-meat-online-1-1024x683.jpg",
  "user_id": 3
}

###Uploads Destroy
DELETE http://localhost:3000/uploads/3.json
Content-Type: application/json

############################################

###Comments Index
GET http://localhost:3000/comments.json
Content-Type: application/json

###Comments Create
POST http://localhost:3000/comments.json
Content-Type: application/json

{
 "user_id": 2,
 "upload_id": 1,
 "comment": "Wow! That looks delciious!" 
}

###Comments Show
GET http://localhost:3000/comments/2.json
Content-Type: application/json

###Comments Update
PATCH http://localhost:3000/comments/2.json
Content-Type: application/json

{
  "user_id": 2,
 "upload_id": 1,
 "comment": "Wow, that looks delciious!" 
}

###Comments Destroy
DELETE http://localhost:3000/comments/3.json
Content-Type: application/json